--- #YAML:1.0
name:               Business-OnlinePayment-CardFortress
version:            0.01
abstract:           CardFortress backend for Business::OnlinePayment
author:
    - Ivan Kohler <ivan-cardfortress@420.am>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Business::OnlinePayment:  0
    Crypt::OpenSSL::RSA:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
